apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: modelmesh-federated-metrics
  labels:
    trustyai-service: trustyai-service
spec:
  endpoints:
    - interval: 30s
      honorLabels: true
      scrapeTimeout: 10s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      bearerTokenSecret:
        key: ""
      port: web
      scheme: https
  namespaceSelector:
    matchNames:
      - openshift-monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: openshift-monitoring
