apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - prometheus
 - prometheus-operator
 - servicemonitors

configMapGenerator:
  - name: model-monitoring-parameters
    envs:
      - params.env
configurations:
  - params.yaml

replacements:
- source:
      kind: ConfigMap
      name: model-monitoring-parameters
      fieldPath: data.deployment-namespace #metadata.namespace
  targets:
  - select:
      kind: Prometheus
      name: odh-model-monitoring
    fieldPaths:
      - spec.containers.[name=oauth-proxy].env.[name=DEPLOYMENT_NAMESPACE].value
  - select:
      kind: ClusterRoleBinding
      name: prometheus-token-access
    fieldPaths:
      - subjects.[name=prometheus-custom].namespace
  - select:
      kind: ServiceAccount
      name: prometheus-custom
    fieldPaths:
      - metadata.namespace
  - select:
      kind: ClusterRoleBinding
      name: odh-namespace-read
    fieldPaths:
      - subjects.[name=prometheus-custom].namespace
  - select:
      kind: ClusterRoleBinding
      name: odh-namespace-read
    fieldPaths:
      - subjects.[name=prometheus-custom].namespace
  - select:
      kind: ClusterRoleBinding
      name: odh-prometheus-operator
    fieldPaths:
      - subjects.[name=odh-prometheus-operator].namespace