apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- odh-prometheus.yaml
- secret.yaml
- service.yaml
- serviceaccount.yaml
- rbac
- route.yaml
vars:
  - name: deployment-namespace
    objref:
      kind: ConfigMap
      name: model-monitoring-parameters
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
  - name: monitoring-namespace
    objref:
      kind: ConfigMap
      name: model-monitoring-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.monitoring-namespace
